from typing import Protocol
from .plugin import Plugin

class PluginManager(Protocol):
    async def load(self, plugin_cls: type[Plugin]) -> Plugin: ...
    async def load_all(self, plugin_classes: list[type[Plugin]]) -> None: ...
    async def start(self, name: str) -> None: ...
    async def stop(self, name: str) -> None: ...
    async def unload(self, name: str) -> None: ...
    async def reload(self, name: str) -> Plugin: ...
    def get(self, name: str) -> Plugin | None: ...
    def list_names(self) -> list[str]: ...
    def is_running(self, name: str) -> bool: ...